image: busybox

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r assets public
    - cp index.html public
    - cp script.js public
    - cp styles.css public
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
